name: swift_transitions_example
description: Example app for the swift_transitions package.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  swift_transitions:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
